# -*- coding: utf-8 -*-
"""AIML-Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SKi6oHtInbgUBqdC6kgXCDHhBysA6I2Y
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import joblib

# Load the dataset
df = pd.read_csv('/content/KaggleV2-May-2016.csv')
print(df.head())

# 1. Rename columns to correct typos and make them easier to work with
df.rename(columns={'Hipertension': 'Hypertension', 'Handcap': 'Handicap', 'No-show':'NoShow'}, inplace=True)

# 2. Convert to datetime AND normalize to midnight (removes the time, keeps the correct format)
df['ScheduledDay'] = pd.to_datetime(df['ScheduledDay']).dt.normalize()
df['AppointmentDay'] = pd.to_datetime(df['AppointmentDay']).dt.normalize()

# 3. FEATURE ENGINEERING: Calculate how many days the patient had to wait
# Now we can safely subtract and extract the days!
df['WaitDays'] = (df['AppointmentDay'] - df['ScheduledDay']).dt.days

# Remove anomalies (WaitDays cannot be negative)
df = df[df['WaitDays'] >= 0]

# 4. Convert Target Variable: 'Yes' (No-show) -> 1, 'No' (Showed up) -> 0
df['NoShow'] = df['NoShow'].map({'Yes': 1, 'No': 0})

# 5. Convert Gender to binary: 'M' -> 1, 'F' -> 0
df['Gender'] = df['Gender'].map({'M': 1, 'F': 0})

# 6. Drop columns that won't help predictions or are too noisy for a basic model
cols_to_drop = ['PatientId', 'AppointmentID', 'ScheduledDay', 'AppointmentDay', 'Neighbourhood']
df = df.drop(columns=cols_to_drop)

print("Data shape after preprocessing:", df.shape)
# Just to double check our fix worked:
print("WaitDays sample:\n", df['WaitDays'].head())

# Separate Features (X) and Target (y)
X = df.drop('NoShow', axis=1)
y = df['NoShow']

# Split data: 80% for training, 20% for testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data (Crucial for Logistic Regression)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("--- Logistic Regression ---")
lr_model = LogisticRegression(max_iter=1000)
# lr_model = LogisticRegression(max_iter=1000, class_weight='balanced')

# Remove rows with NaN values from X_train_scaled and y_train
nan_mask_train = np.isnan(X_train_scaled).any(axis=1) | y_train.isnull()
X_train_scaled_cleaned = X_train_scaled[~nan_mask_train]
y_train_cleaned = y_train[~nan_mask_train]

# Fit the model with cleaned data
lr_model.fit(X_train_scaled_cleaned, y_train_cleaned)

# Remove rows with NaN values from X_test_scaled and y_test for prediction and evaluation
nan_mask_test = np.isnan(X_test_scaled).any(axis=1) | y_test.isnull()
X_test_scaled_cleaned = X_test_scaled[~nan_mask_test]
y_test_cleaned = y_test[~nan_mask_test]

lr_preds = lr_model.predict(X_test_scaled_cleaned)
print("Accuracy:", accuracy_score(y_test_cleaned, lr_preds))
print(classification_report(y_test_cleaned, lr_preds))

print("--- Decision Tree ---")
# Constraining depth prevents overfitting
dt_model = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_model.fit(X_train_scaled_cleaned, y_train_cleaned)

dt_preds = dt_model.predict(X_test_scaled_cleaned)
print("Accuracy:", accuracy_score(y_test_cleaned, dt_preds))
print(classification_report(y_test_cleaned, dt_preds))

# Get Feature Importance for your UI and Report
feature_importances = pd.DataFrame({
    'Feature': X.columns,
    'Importance': dt_model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("\nFeature Importances:\n", feature_importances)

# Let's say Decision Tree performed best (or you just prefer it for feature importance)
best_model = dt_model

# Save the model and the scaler
joblib.dump(best_model, 'noshow_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

print("Model and Scaler exported successfully! Download them from the left sidebar.")